import { Book } from "@/types/books.types";

export const BooksData: Book[] = [
  {
    book_id: "BK-7431",
    title: "The Great Adventure",
    author: "John Doe",
    yearPublished: 2021,
    genre: "Adventure",
    chapters: [
      {
        chapter_id: "CH-9123",
        title: "Chapter 1: The Beginning",
        pages: 25,
        summary: "The protagonist embarks on their journey.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-8472",
        title: "Chapter 2: Into the Wild",
        pages: 30,
        summary: "The protagonist faces challenges in the wilderness.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3914",
        title: "Chapter 3: The Final Battle",
        pages: 45,
        summary: "The protagonist confronts the antagonist.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-5823",
        title: "Chapter 4: The Aftermath",
        pages: 20,
        summary: "The protagonist reflects on the journey.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-5284",
    title: "Mystery of the Lost City",
    author: "Jane Smith",
    yearPublished: 2019,
    genre: "Mystery",
    chapters: [
      {
        chapter_id: "CH-7521",
        title: "Chapter 1: The Discovery",
        pages: 22,
        summary: "Archaeologists find a hidden city.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6213",
        title: "Chapter 2: Unveiling Secrets",
        pages: 35,
        summary: "The team uncovers the city's secrets.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3749",
        title: "Chapter 3: The Hidden Treasure",
        pages: 40,
        summary: "A treasure is found in the city's ruins.",
        chapterNumber: 3,
        isImportant: true,
      },
    ],
  },
  {
    book_id: "BK-1693",
    title: "The Science of Tomorrow",
    author: "Emily Turner",
    yearPublished: 2023,
    genre: "Science Fiction",
    chapters: [
      {
        chapter_id: "CH-8431",
        title: "Chapter 1: The Invention",
        pages: 18,
        summary: "A scientist invents a time machine.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6512",
        title: "Chapter 2: First Journey",
        pages: 28,
        summary: "The first test of the time machine.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3972",
        title: "Chapter 3: Future Shock",
        pages: 32,
        summary: "The scientist travels to the future.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-2794",
        title: "Chapter 4: Returning Home",
        pages: 24,
        summary: "The scientist returns to the present.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-4827",
    title: "The Chronicles of Eldoria",
    author: "Michael Brown",
    yearPublished: 2020,
    genre: "Fantasy",
    chapters: [
      {
        chapter_id: "CH-9324",
        title: "Chapter 1: The Prophecy",
        pages: 30,
        summary: "A prophecy foretells the rise of a hero.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6832",
        title: "Chapter 2: The Gathering",
        pages: 38,
        summary: "Heroes from across the land gather.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4927",
        title: "Chapter 3: The Battle of Shadows",
        pages: 50,
        summary: "A great battle between light and dark.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-2749",
        title: "Chapter 4: The Dawn of Peace",
        pages: 27,
        summary: "Peace is restored to Eldoria.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-5917",
    title: "The History of Civilizations",
    author: "Sarah Johnson",
    yearPublished: 2018,
    genre: "History",
    chapters: [
      {
        chapter_id: "CH-8423",
        title: "Chapter 1: Ancient Empires",
        pages: 45,
        summary: "An overview of ancient empires.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-5732",
        title: "Chapter 2: The Middle Ages",
        pages: 40,
        summary: "Key events during the Middle Ages.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4982",
        title: "Chapter 3: The Renaissance",
        pages: 35,
        summary: "The cultural rebirth of Europe.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-6293",
        title: "Chapter 4: The Industrial Revolution",
        pages: 50,
        summary: "The rise of industry and modern society.",
        chapterNumber: 4,
        isImportant: true,
      },
      {
        chapter_id: "CH-7251",
        title: "Chapter 5: The Modern Era",
        pages: 30,
        summary: "Major events of the 20th and 21st centuries.",
        chapterNumber: 5,
        isImportant: true,
      },
    ],
  },
  {
    book_id: "BK-3146",
    title: "Journey Through the Stars",
    author: "Robert Wilson",
    yearPublished: 2022,
    genre: "Science Fiction",
    chapters: [
      {
        chapter_id: "CH-9127",
        title: "Chapter 1: The Launch",
        pages: 20,
        summary: "A spacecraft is launched on a deep space mission.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-5382",
        title: "Chapter 2: Alien Encounter",
        pages: 35,
        summary: "The crew encounters an alien species.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4216",
        title: "Chapter 3: The Return Journey",
        pages: 40,
        summary: "The crew returns to Earth with new knowledge.",
        chapterNumber: 3,
        isImportant: true,
      },
    ],
  },
];
